version: '3'
services:
  api:
    build: ./flask-server
    container_name: flask-server
    ports:
      - "5000:5000"
  
  web:
    build: ./client
    container_name: react-client
    ports:
      - "3000:80"
    depends_on:
      - api
